#page title
page_title                                : "Receipts"                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1584452416                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Organize and store your receipts and business expenses on your iPhone with the Receipts app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Nineone Software Inc.                                
your_link                                 :                      
your_city                                 : Vancouver                                
email_address                             : nineonesoftware@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.    2. Import photos from your Photo Library from an album you've created in WorkCam 3. Send up to 50 photos at a time from your Photo Library to WorkCam via the iOS share sheet
features                                  :
  - title                                 : Document Scanning
    description                           : Quickly scan receipts with the Receipts app. Scanned receipts will automatically be processed with computer vision for easy entry and searching.
    fontawesome_icon_name                 : sync

  - title                                 : Import Files & Photos
    description                           : Quickly and easily import your receipt documents and photos from your iPhone's Files or Photo Library. The Receipts app can process image files as well as PDFs.
    fontawesome_icon_name                 : sync

  - title                                 : Organize
    description                           : Create an unlimited amount of expenses and categories e.g. 'Office Supplies', 'Marketing', 'Advertisements' etc. Associate each of your expenses with a category for easy search-ability and filtering.
    fontawesome_icon_name                 : adjust

  - title                                 : Computer Vision
    description                           : When you scan a receipt with the Receipts app's document scanner the app's computer vision processes any found text and values detected on the receipt.
    fontawesome_icon_name                 : magic
  
  - title                                 : Security
    description                           : All documents and images stored with the Receipts app are securely encrypted with Apple's file encryption system.
    fontawesome_icon_name                 : star

  - title                                 : Export
    description                           : All expenses and receipts stored with the Receipts app can be exported as PDF Expense Reports. Your expenses within the Receipts app can also be exported as comma-separated values (CSV) files for sharing with your account or inserted into Excel sheets.
    fontawesome_icon_name                 : arrow-alt-circle-up

  - title                                 : Search
    description                           : Receipts that are processed with the Receipts app have all associated text indexed and searchable. This means that you can search your expenses by name, dollar amount, and even any text contained within a receipt!
    fontawesome_icon_name                 : magic


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/vancouva.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#ffffff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#6C63FF"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"






####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown